-- ============================================================================
-- Migration: 001_initial.sql
-- Description: Initial schema — profiles, schema_version, and audit_events.
--
-- RULES:
--  - Never edit an applied migration (Evolution Plan §8).
--  - Use expand-and-contract for schema changes.
--  - Every table includes owner_id, created_at; mutable tables include updated_at.
--  - Boolean values: INTEGER constrained to 0 or 1.
--  - Timestamps: UTC ISO-8601 TEXT with application validation.
--  - IDs: UUID TEXT generated by Worker.
--
-- Database Model references: §6 (field conventions), §16 (migrations).
-- ============================================================================

-- D1 controls its own journaling mode; attempting PRAGMA journal_mode = WAL
-- is rejected with SQLITE_AUTH by Wrangler's D1 runtime.
PRAGMA foreign_keys = ON;

-- ----------------------------------------------------------------------------
-- Schema version tracking
-- Every migration must update this table.
-- The version is also stored in every export package.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schema_versions (
  version         INTEGER PRIMARY KEY,
  description     TEXT    NOT NULL,
  applied_at      TEXT    NOT NULL, -- UTC ISO-8601
  checksum        TEXT    -- SHA-256 of the migration file for integrity
);

INSERT INTO schema_versions (version, description, applied_at)
VALUES (1, 'Initial schema: profiles, audit_events, schema_versions', datetime('now'));

-- ----------------------------------------------------------------------------
-- Profiles — canonical identity
-- Database Model §4 (Identity and publication)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profiles (
  id              TEXT    PRIMARY KEY,                      -- UUID
  owner_id        TEXT    NOT NULL,                         -- MUST match Access JWT subject
  display_name    TEXT    NOT NULL,
  headline        TEXT,                                     -- factual, owner-approved
  bio             TEXT,                                     -- approved narrative
  current_focus   TEXT,                                     -- truthful current positioning
  contact_email   TEXT,                                     -- private; served via authorized endpoint
  contact_url     TEXT,
  timezone        TEXT    NOT NULL DEFAULT 'UTC',           -- IANA timezone
  visibility      TEXT    NOT NULL DEFAULT 'private'        -- new records default to private
                          CHECK (visibility IN ('private', 'restricted', 'unlisted', 'public')),
  created_at      TEXT    NOT NULL,                         -- UTC ISO-8601
  updated_at      TEXT    NOT NULL,                         -- UTC ISO-8601
  version_no      INTEGER NOT NULL DEFAULT 1                -- optimistic concurrency
);

-- Only one profile per owner
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_owner ON profiles (owner_id);

-- ----------------------------------------------------------------------------
-- Audit events — append-only security audit log
-- Database Model §4, Security Threat Model §6 (audit tampering — high risk)
-- SECURITY: Append-oriented; no UI hard-delete permitted.
-- SECURITY: Logs must not contain evidence bodies, secrets or AI prompts.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_events (
  id              TEXT    PRIMARY KEY,                      -- UUID
  owner_id        TEXT    NOT NULL,
  event_type      TEXT    NOT NULL,
  entity_type     TEXT,                                     -- safe type string only
  entity_id       TEXT,                                     -- safe ID only
  action          TEXT    NOT NULL,
  actor_subject   TEXT    NOT NULL,                         -- authenticated subject from JWT
  request_id      TEXT    NOT NULL,
  occurred_at     TEXT    NOT NULL,                         -- UTC ISO-8601
  -- SECURITY: No evidence body, no secrets, no private content, no AI prompts
  -- Metadata is a safe JSON object (entity type, action, status code only)
  safe_metadata   TEXT,                                     -- validated JSON
  ip_hash         TEXT                                      -- hashed, never raw IP
);

-- Query by owner and time for dashboard audit view
CREATE INDEX IF NOT EXISTS idx_audit_events_owner_time
  ON audit_events (owner_id, occurred_at DESC);

-- Query by entity for dependency inspection
CREATE INDEX IF NOT EXISTS idx_audit_events_entity
  ON audit_events (entity_type, entity_id, occurred_at DESC);
