version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: Asia/Karachi
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production
    labels:
      - dependencies
      - automated

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - github-actions
