export * from './github-types.js';

// ---------------------------------------------------------------------------
// Shared primitives
// ---------------------------------------------------------------------------

/** Opaque UUID string generated by the Worker — never accepted from client. */
export type EntityId = string & { readonly __brand: 'EntityId' };

/** UTC ISO-8601 datetime string. */
export type ISODateTime = string & { readonly __brand: 'ISODateTime' };

/** ISO YYYY-MM-DD date string. */
export type ISODate = string & { readonly __brand: 'ISODate' };

// ---------------------------------------------------------------------------
// Visibility — Section 7 of Database Model
// A record is publicly discoverable ONLY when ALL of these conditions are met:
//  1. Effective visibility is "public"
//  2. State is "published"
//  3. Not archived/deleted
//  4. Any embargo has expired
// ---------------------------------------------------------------------------

export type Visibility = 'private' | 'restricted' | 'unlisted' | 'public';

export type PublicationState =
  'draft' | 'review' | 'approved' | 'scheduled' | 'published' | 'unlisted' | 'archived';

// ---------------------------------------------------------------------------
// Evidence — Section 3, 8, 9 of Database Model
// A verifiable record that work, learning or delivery occurred.
// ---------------------------------------------------------------------------

export type EvidenceType =
  | 'journal_entry'
  | 'source_code_contribution'
  | 'commit'
  | 'pull_request'
  | 'repository'
  | 'deployment'
  | 'project_artifact'
  | 'experiment'
  | 'adr'
  | 'debugging_lesson'
  | 'certification'
  | 'education_record'
  | 'employment_record'
  | 'external_publication'
  | 'manual_evidence'
  | 'work_record'
  | 'certificate'
  | 'publication'
  | 'contribution'
  | 'artifact'
  | 'other';

export type EvidenceSourceType =
  'github' | 'url' | 'file' | 'manual' | 'integration' | 'owner_attested';

/**
 * Verification states for evidence.
 * An evidence item transitions through these states.
 * "archived" and "broken" flag dependent claims as unhealthy.
 */
export type EvidenceVerificationState =
  | 'unverified'
  | 'unreviewed'
  | 'owner_verified'
  | 'source_verified'
  | 'automatically_observed'
  | 'stale'
  | 'broken'
  | 'disputed'
  | 'revoked'
  | 'archived';

/** Evidence verification audit event entity — append-only verification history. */
export interface EvidenceVerificationEventEntity {
  readonly id: EntityId;
  readonly evidenceItemId: EntityId;
  readonly ownerId: EntityId;
  readonly previousState: EvidenceVerificationState | null;
  readonly newState: EvidenceVerificationState;
  readonly verificationMethod: string;
  readonly verifierIdentity: string;
  readonly rationale: string | null;
  readonly createdAt: ISODateTime;
}

/** Evidence support edge type — models the relationship quality. */
export type EvidenceSupportType =
  | 'demonstrates' // direct evidence of implementation, delivery, explanation or outcome
  | 'corroborates' // supporting context — insufficient alone
  | 'historical' // proves past activity but may be stale
  | 'contradicts'; // invalidates or challenges an assertion

// ---------------------------------------------------------------------------
// Skill — Section 3 of Database Model
// A taxonomy node. A skill does NOT assert proficiency.
// INVARIANT: No numeric proficiency field may ever be added to this type.
// ---------------------------------------------------------------------------

export interface SkillEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly name: string;
  readonly slug: string;
  readonly description: string | null;
  readonly parentId: EntityId | null; // taxonomy hierarchy
  readonly aliases: readonly string[];
  readonly visibility: Visibility;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
  readonly versionNo: number;
  // INVARIANT: No proficiencyLevel, proficiencyPercent or similar field exists.
}

// ---------------------------------------------------------------------------
// Capability — Section 3, 10 of Database Model
// A bounded observable ability, e.g. "implements 2D linear transforms with NumPy."
// Maturity is DESCRIPTIVE, not numeric.
// ---------------------------------------------------------------------------

/**
 * Descriptive maturity states — Section 10.
 * INVARIANT: Maturity must never be represented as a percentage or numeric value.
 * Maturity is derived from evidence breadth, depth, independence, recency and outcomes,
 * then APPROVED BY THE OWNER.
 */
export type CapabilityMaturity =
  | 'not_enough_evidence'
  | 'exploring'
  | 'practicing'
  | 'applying'
  | 'demonstrated'
  | 'sustained'
  | 'leadership';

export interface CapabilityEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly title: string; // bounded, observable, specific
  readonly slug: string;
  readonly description: string;
  readonly outcomeStatement: string; // bounded outcome description
  readonly maturity: CapabilityMaturity;
  readonly maturityRationale: string; // required — explains the maturity state
  readonly maturityRuleVersion: string; // versioned rule set
  readonly qualifyingEvidenceRules: string; // JSON text — what evidence qualifies
  readonly visibility: Visibility;
  readonly state: PublicationState;
  readonly lifecycleState: SkillLifecycleState;
  readonly ownerConfirmed: boolean;
  readonly firstDemonstratedAt: ISODateTime | null;
  readonly lastDemonstratedAt: ISODateTime | null;
  readonly provenanceMetadata: string; // JSON
  readonly skillIds: readonly EntityId[]; // linked taxonomy nodes
  readonly lastReviewedAt: ISODate | null;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
  readonly versionNo: number;
  // INVARIANT: No percentage, score, or numeric proficiency field.
}

// ---------------------------------------------------------------------------
// Milestone M4 — Skills & Capabilities Graph Entity Models
// ---------------------------------------------------------------------------

export type SkillCategory =
  | 'programming_language'
  | 'framework_library'
  | 'tool_platform'
  | 'architecture'
  | 'data'
  | 'security'
  | 'testing'
  | 'devops_infrastructure'
  | 'design_accessibility'
  | 'engineering_practice'
  | 'communication_leadership'
  | 'domain_knowledge';

export type SkillType = 'technical' | 'domain' | 'methodology' | 'soft';

export type SkillLifecycleState = 'draft' | 'active' | 'deprecated' | 'archived';

export type SkillRelationshipType =
  'parent_child' | 'related' | 'prerequisite' | 'complementary' | 'supersedes' | 'applied_with';

export type CapabilitySkillRelationshipType = 'required' | 'supporting' | 'complementary';

export type EvidenceSkillRelationshipType =
  | 'introduces'
  | 'practices'
  | 'applies'
  | 'demonstrates'
  | 'sustains'
  | 'validates'
  | 'refreshes'
  | 'contradicts';

export type EvidenceCapabilityRelationshipType =
  'supports' | 'demonstrates' | 'validates' | 'contradicts';

export type ProgressionStage =
  'exploring' | 'practicing' | 'applying' | 'demonstrated' | 'sustained' | 'leadership';

export type CreatedByClassification = 'owner' | 'system' | 'suggestion';

export type ApprovalState = 'pending' | 'accepted' | 'rejected';

export interface SkillRelationshipEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly sourceSkillId: EntityId;
  readonly targetSkillId: EntityId;
  readonly relationshipType: SkillRelationshipType;
  readonly relevance: number; // 1–5
  readonly ordering: number;
  readonly evidenceProvenance: string; // JSON
  readonly createdByClassification: CreatedByClassification;
  readonly approvalState: ApprovalState;
  readonly ownerNote: string | null;
  readonly createdAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
}

export interface CapabilitySkillRelationshipEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly capabilityId: EntityId;
  readonly skillId: EntityId;
  readonly relationshipType: CapabilitySkillRelationshipType;
  readonly relevance: number; // 1–5
  readonly ordering: number;
  readonly evidenceProvenance: string; // JSON
  readonly createdByClassification: CreatedByClassification;
  readonly approvalState: ApprovalState;
  readonly ownerNote: string | null;
  readonly createdAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
}

export interface EvidenceSkillLinkEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly evidenceId: EntityId;
  readonly skillId: EntityId;
  readonly relationshipType: EvidenceSkillRelationshipType;
  readonly relevance: number; // 1–5
  readonly ordering: number;
  readonly evidenceProvenance: string; // JSON
  readonly createdByClassification: CreatedByClassification;
  readonly approvalState: ApprovalState;
  readonly ownerNote: string | null;
  readonly createdAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
}

export interface EvidenceCapabilityLinkEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly evidenceId: EntityId;
  readonly capabilityId: EntityId;
  readonly relationshipType: EvidenceCapabilityRelationshipType;
  readonly relevance: number; // 1–5
  readonly ordering: number;
  readonly evidenceProvenance: string; // JSON
  readonly createdByClassification: CreatedByClassification;
  readonly approvalState: ApprovalState;
  readonly ownerNote: string | null;
  readonly createdAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
}

export type ProgressionActor = 'owner' | 'system' | 'suggestion';

export interface ProgressionEventEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly skillId: EntityId | null;
  readonly capabilityId: EntityId | null;
  readonly previousStage: ProgressionStage | null;
  readonly newStage: ProgressionStage;
  readonly supportingEvidenceIds: readonly EntityId[];
  readonly reason: string;
  readonly actorClassification: ProgressionActor;
  readonly approvalState: ApprovalState;
  readonly supersedesEventId: EntityId | null;
  readonly createdAt: ISODateTime;
}

export type SuggestionType =
  | 'possible_skill'
  | 'possible_evidence_skill_link'
  | 'possible_capability'
  | 'possible_progression_event'
  | 'possible_related_skill';

export type SuggestionState =
  'pending' | 'accepted' | 'edited_and_accepted' | 'rejected' | 'superseded' | 'expired';

export type SuggestionOrigin = 'deterministic_rule' | 'system' | 'ai_model';

export interface SuggestionEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly suggestionType: SuggestionType;
  readonly title: string;
  readonly description: string;
  readonly payloadJson: string;
  readonly evidenceReferences: readonly EntityId[];
  readonly createdByClassification: SuggestionOrigin;
  readonly modelMetadataJson: string;
  readonly suggestionState: SuggestionState;
  readonly rejectionReason: string | null;
  readonly fingerprint: string;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
}

export type EvidenceStrength =
  'limited_evidence' | 'emerging_evidence' | 'established_evidence' | 'strong_evidence';

// ---------------------------------------------------------------------------
// Claim — Section 3, 11 of Database Model
// An owner-approved professional statement.
// INVARIANT: Cannot be published without approved supporting evidence
//            (or a narrowly permitted audited background-statement exception).
// ---------------------------------------------------------------------------

export type ClaimApprovalState = 'draft' | 'pending' | 'approved' | 'rejected' | 'expired';

export type ClaimAudience = 'recruiter' | 'technical' | 'general' | 'resume';

export interface ClaimEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly wording: string; // exact approved wording — owner must approve changes
  readonly audience: ClaimAudience;
  readonly context: string | null;
  readonly approvalState: ClaimApprovalState;
  readonly approvedAt: ISODateTime | null;
  readonly approvedWording: string | null; // immutable snapshot of approved wording
  readonly reviewDate: ISODate | null; // when to re-verify
  readonly isBackgroundStatementException: boolean; // narrowly permitted exception
  readonly backgroundStatementExceptionReason: string | null;
  readonly visibility: Visibility;
  readonly state: PublicationState;
  readonly versionNo: number;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
}

// ---------------------------------------------------------------------------
// Evidence Item — Section 8 of Database Model
// ---------------------------------------------------------------------------

export interface EvidenceItemEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly evidenceType: EvidenceType;
  readonly sourceType: EvidenceSourceType;
  readonly provider: string | null; // e.g. "github"
  readonly externalId: string | null; // provider-specific ID
  readonly canonicalLocator: string | null; // durable URL or path
  readonly title: string;
  readonly description: string | null;
  readonly providerCreatedAt: ISODateTime | null;
  readonly providerUpdatedAt: ISODateTime | null;
  readonly capturedAt: ISODateTime;
  readonly occurredAt: ISODateTime | null; // when the work actually happened
  readonly contentHash: string | null;
  readonly authorshipNote: string | null;
  readonly provenanceSnapshot: string | null; // immutable JSON snapshot
  readonly licenseMetadata: string | null; // JSON
  readonly confidentialityMetadata: string | null; // JSON
  readonly verificationState: EvidenceVerificationState;
  readonly verificationMethod: string | null;
  readonly verifiedBy: string | null;
  readonly verifiedAt: ISODateTime | null;
  readonly qualitySignals: string | null; // JSON — explainable, never a score
  readonly visibility: Visibility;
  readonly embargoUntil: ISODateTime | null;
  readonly versionNo: number;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
}

// ---------------------------------------------------------------------------
// Evidence Link — Section 9 of Database Model
// A typed edge: one evidence item supports exactly ONE target.
// INVARIANT: Every edge references one evidence item and exactly one target.
// ---------------------------------------------------------------------------

export type EvidenceLinkTarget =
  | { targetType: 'capability'; targetId: EntityId }
  | { targetType: 'claim'; targetId: EntityId }
  | { targetType: 'project'; targetId: EntityId }
  | { targetType: 'content_item'; targetId: EntityId }
  | { targetType: 'artifact'; targetId: EntityId }
  | { targetType: 'adr'; targetId: EntityId }
  | { targetType: 'experiment'; targetId: EntityId }
  | { targetType: 'debugging_lesson'; targetId: EntityId }
  | { targetType: 'deployment'; targetId: EntityId }
  | { targetType: 'resume_statement'; targetId: EntityId };

export type EvidenceLinkApprovalState = 'pending' | 'approved' | 'rejected';

export interface EvidenceLinkEntity {
  readonly id: EntityId;
  readonly evidenceItemId: EntityId;
  readonly target: EvidenceLinkTarget; // exactly one target (discriminated union)
  readonly supportType: EvidenceSupportType;
  readonly relevance: number; // 1–5 scale
  readonly ordering: number;
  readonly provenance: string | null;
  readonly rationale: string;
  readonly approvalState: EvidenceLinkApprovalState;
  readonly approvedBy: string | null;
  readonly approvedAt: ISODateTime | null;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
}

// ---------------------------------------------------------------------------
// Artifact — Produced object stored in R2
// ---------------------------------------------------------------------------

export interface ArtifactEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly title: string;
  readonly description: string | null;
  readonly artifactType: string;
  readonly mediaType: string | null;
  readonly byteSize: number | null;
  readonly checksum: string | null;
  readonly r2Key: string;
  readonly r2PublicKey: string | null;
  readonly originalName: string | null;
  readonly uploadedBy: string | null;
  readonly visibility: Visibility;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly deletedAt: ISODateTime | null;
  readonly archivedAt: ISODateTime | null;
}

// ---------------------------------------------------------------------------
// Activity — Section 12 of Database Model
// Normalized dated event for chronology and heatmap.
// INVARIANT: Activity is NOT a competence score.
// ---------------------------------------------------------------------------

export type ActivityType =
  | 'journal_entry'
  | 'evidence_captured'
  | 'capability_updated'
  | 'project_milestone'
  | 'deployment'
  | 'experiment'
  | 'learning'
  | 'other';

export interface ActivityEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly activityType: ActivityType;
  readonly occurredAt: ISODateTime;
  readonly capturedAt: ISODateTime;
  readonly sourceIdentity: string | null; // deduplication key
  readonly dedupKey: string | null;
  readonly visibility: Visibility;
  readonly isExcluded: boolean; // excluded from public aggregation
  readonly visualizationPoints: number; // for display weight, not competence
  readonly entityRef: string | null; // JSON reference to related entity
}

// ---------------------------------------------------------------------------
// Profile — Identity
// ---------------------------------------------------------------------------

export interface ProfileEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly displayName: string;
  readonly headline: string | null; // factual, owner-approved
  readonly bio: string | null; // approved narrative
  readonly currentFocus: string | null; // truthful current positioning
  readonly contactEmail: string | null;
  readonly contactUrl: string | null;
  readonly timezone: string; // IANA timezone for activity aggregation
  readonly visibility: Visibility;
  readonly availabilityState: AvailabilityState;
  readonly preferredRoles: string | null;
  readonly profileImageUrl: string | null;
  readonly resumeAssetUrl: string | null;
  readonly location: string | null;
  readonly versionNo: number;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
}

// ---------------------------------------------------------------------------
// AI Proposal — proposal-only; never auto-approved
// ---------------------------------------------------------------------------

export type ProposalState =
  'pending' | 'under_review' | 'approved' | 'rejected' | 'superseded' | 'expired';

export type ProposalRiskLevel = 'low' | 'medium' | 'high' | 'critical';

export interface AiProposalEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly proposalType: string;
  readonly targetEntityType: string;
  readonly targetEntityId: EntityId | null;
  readonly state: ProposalState;
  readonly riskLevel: ProposalRiskLevel;
  readonly confidence: number | null; // 0.0–1.0 model confidence — not a proficiency
  readonly rationale: string;
  readonly sourceContext: string | null; // sanitized context used
  readonly modelVersion: string;
  readonly promptVersion: string;
  readonly createdAt: ISODateTime;
  readonly reviewedAt: ISODateTime | null;
  readonly reviewedBy: string | null;
  readonly expiresAt: ISODateTime | null;
}

// ---------------------------------------------------------------------------
// Content Item — Journal & Content Engine (Database Model §4)
// ---------------------------------------------------------------------------

export type ContentType = 'note' | 'journal' | 'deep_dive' | 'retrospective';

export interface ContentItemEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly contentType: ContentType;
  readonly title: string;
  readonly slug: string;
  readonly summary: string | null;
  readonly bodyFormat: 'json_blocks' | 'markdown';
  readonly bodySchemaVersion: string;
  readonly readingTimeMinutes: number | null;
  readonly visibility: Visibility;
  readonly state: PublicationState;
  readonly occurredAt: ISODateTime | null;
  readonly publishedAt: ISODateTime | null;
  readonly scheduledFor: ISODateTime | null;
  readonly embargoUntil: ISODateTime | null;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
  readonly deletedAt: ISODateTime | null;
  readonly versionNo: number;
}

export interface ContentRevisionEntity {
  readonly id: EntityId;
  readonly contentItemId: EntityId;
  readonly ownerId: EntityId;
  readonly revisionNo: number;
  readonly bodySnapshot: string;
  readonly bodySchemaVersion: string;
  readonly revisionNote: string | null;
  readonly createdAt: ISODateTime;
  readonly createdBy: string;
}

// ---------------------------------------------------------------------------
// Project & Engineering Record — Milestone M5
// ---------------------------------------------------------------------------

export type ProjectLifecycleState =
  'idea' | 'planning' | 'active' | 'paused' | 'completed' | 'maintained' | 'archived' | 'cancelled';

export interface ProjectEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly title: string;
  readonly slug: string;
  readonly shortSummary: string | null;
  readonly detailedContext: string | null;
  readonly problemStatement: string | null;
  readonly goals: readonly string[];
  readonly nonGoals: readonly string[];
  readonly constraints: readonly string[];
  readonly role: string | null;
  readonly contributionStatement: string | null;
  readonly collaborationContext: string | null;
  readonly startDate: string | null;
  readonly endDate: string | null;
  readonly ongoingStatus: boolean;
  readonly lifecycleState: ProjectLifecycleState;
  readonly publicationState: PublicationState;
  readonly visibility: Visibility;
  readonly scheduledFor: ISODateTime | null;
  readonly embargoUntil: ISODateTime | null;
  readonly isFeatured: boolean;
  readonly recruiterSummary: string | null;
  readonly deepDiveContent: string | null;
  readonly repositoryReferences: readonly string[];
  readonly liveDemoReferences: readonly string[];
  readonly heroArtifactId: EntityId | null;
  readonly caseStudyBody: string | null;
  readonly caseStudyFormat?: string | null;
  readonly caseStudySchemaVersion?: number | null;
  readonly editorialWarnings?: readonly string[];
  readonly provenance: string | null;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
  readonly deletedAt: ISODateTime | null;
  readonly versionNo: number;
}

export type ProjectContributionType =
  | 'designed'
  | 'implemented'
  | 'tested'
  | 'debugged'
  | 'documented'
  | 'deployed'
  | 'maintained'
  | 'reviewed'
  | 'led'
  | 'collaborated'
  | 'researched';

export interface ProjectContributionEntity {
  readonly id: EntityId;
  readonly projectId: EntityId;
  readonly ownerId: EntityId;
  readonly contributionType: ProjectContributionType;
  readonly description: string;
  readonly scope: string | null;
  readonly startDate: string | null;
  readonly endDate: string | null;
  readonly collaborationContext: string | null;
  readonly supportingEvidenceIds: readonly EntityId[];
  readonly verificationState: EvidenceVerificationState;
  readonly visibility: Visibility;
  readonly ownerApproval: boolean;
  readonly provenance: string | null;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly deletedAt: ISODateTime | null;
}

export type ExperimentStatus = 'planned' | 'in_progress' | 'concluded' | 'abandoned';

export interface ExperimentEntity {
  readonly id: EntityId;
  readonly projectId: EntityId;
  readonly ownerId: EntityId;
  readonly title: string;
  readonly slug: string;
  readonly hypothesis: string;
  readonly motivation: string | null;
  readonly methodology: string;
  readonly variables: readonly string[];
  readonly inputs: string | null;
  readonly results: string | null;
  readonly conclusion: string | null;
  readonly limitations: string | null;
  readonly status: ExperimentStatus;
  readonly dates: string | null;
  readonly supportingEvidenceIds: readonly EntityId[];
  readonly artifactIds: readonly EntityId[];
  readonly visibility: Visibility;
  readonly state: PublicationState;
  readonly provenance: string | null;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
  readonly deletedAt: ISODateTime | null;
  readonly versionNo: number;
}

export type ProjectAdrStatus = 'proposed' | 'accepted' | 'rejected' | 'superseded' | 'deprecated';

export interface ProjectAdrEntity {
  readonly id: EntityId;
  readonly projectId: EntityId;
  readonly ownerId: EntityId;
  readonly adrNumber: number;
  readonly title: string;
  readonly slug: string;
  readonly status: ProjectAdrStatus;
  readonly context: string;
  readonly alternativesConsidered: readonly string[];
  readonly decision: string;
  readonly rationale: string | null;
  readonly consequences: string;
  readonly tradeOffs: string | null;
  readonly relatedAdrIds: readonly EntityId[];
  readonly supersededBy: EntityId | null;
  readonly decisionDate: string | null;
  readonly supportingEvidenceIds: readonly EntityId[];
  readonly visibility: Visibility;
  readonly state: PublicationState;
  readonly provenance: string | null;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
  readonly deletedAt: ISODateTime | null;
  readonly versionNo: number;
}

export interface DebuggingLessonEntity {
  readonly id: EntityId;
  readonly projectId: EntityId;
  readonly ownerId: EntityId;
  readonly title: string;
  readonly slug: string;
  readonly symptom: string;
  readonly impact: string | null;
  readonly environment: string | null;
  readonly investigation: string | null;
  readonly rootCause: string;
  readonly resolution: string;
  readonly prevention: string;
  readonly lessonsLearned: string | null;
  readonly relevantDates: string | null;
  readonly tags: readonly string[];
  readonly supportingEvidenceIds: readonly EntityId[];
  readonly artifactIds: readonly EntityId[];
  readonly visibility: Visibility;
  readonly state: PublicationState;
  readonly provenance: string | null;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
  readonly deletedAt: ISODateTime | null;
  readonly versionNo: number;
}

export type DeploymentEnvironment = 'preview' | 'staging' | 'production';

export type DeploymentStatus = 'pending' | 'success' | 'failed' | 'rolled_back';

export interface DeploymentEntity {
  readonly id: EntityId;
  readonly projectId: EntityId;
  readonly ownerId: EntityId;
  readonly environment: DeploymentEnvironment;
  readonly releaseVersion: string;
  readonly gitSha: string | null;
  readonly deploymentUrl: string | null;
  readonly status: DeploymentStatus;
  readonly startedAt: ISODateTime | null;
  readonly deployedAt: ISODateTime;
  readonly rollbackInfo: string | null;
  readonly outcome: string | null;
  readonly supportingEvidenceIds: readonly EntityId[];
  readonly artifactIds: readonly EntityId[];
  readonly visibility: Visibility;
  readonly publicationState: PublicationState;
  readonly provenance: string | null;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly deletedAt: ISODateTime | null;
}

export type ProjectVersionStatus =
  'planned' | 'in_progress' | 'released' | 'deprecated' | 'archived';

export interface ProjectVersionEntity {
  readonly id: EntityId;
  readonly projectId: EntityId;
  readonly ownerId: EntityId;
  readonly name: string;
  readonly versionIdentifier: string;
  readonly description: string | null;
  readonly status: ProjectVersionStatus;
  readonly startedDate: string | null;
  readonly completedDate: string | null;
  readonly changelog: string | null;
  readonly outcome: string | null;
  readonly supportingEvidenceIds: readonly EntityId[];
  readonly artifactIds: readonly EntityId[];
  readonly previousVersionId: EntityId | null;
  readonly visibility: Visibility;
  readonly state: PublicationState;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly deletedAt: ISODateTime | null;
}

export interface ProjectRelationshipEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly sourceId: EntityId;
  readonly sourceType: string;
  readonly targetId: EntityId;
  readonly targetType: string;
  readonly relationshipType: string;
  readonly relevance: number;
  readonly displayOrder: number;
  readonly provenance: string | null;
  readonly createdByClassification: CreatedByClassification;
  readonly approvalState: ApprovalState;
  readonly ownerNote: string | null;
  readonly createdAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
}

export interface ProjectRevisionEntity {
  readonly id: EntityId;
  readonly projectId: EntityId;
  readonly ownerId: EntityId;
  readonly revisionNo: number;
  readonly caseStudySnapshot: string;
  readonly bodyFormat?: string | null;
  readonly bodySchemaVersion?: number | null;
  readonly markdownExport?: string | null;
  readonly redactionMetadata?: readonly string[];
  readonly revisionNote: string | null;
  readonly createdAt: ISODateTime;
  readonly createdBy: string;
}

// ---------------------------------------------------------------------------
// Milestone M7 Professional Identity & Résumé Engine Domain Entity Types
// ---------------------------------------------------------------------------

export type AvailabilityState = 'available' | 'open' | 'unavailable' | 'busy';

export type PublicationEligibility = 'eligible' | 'ineligible' | 'pending_review';

export interface ProfileExtensionEntity {
  readonly availabilityState: AvailabilityState;
  readonly preferredRoles: string | null;
  readonly profileImageUrl: string | null;
  readonly resumeAssetUrl: string | null;
  readonly location: string | null;
}

export interface ExperienceRecordEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly company: string;
  readonly roleTitle: string;
  readonly location: string | null;
  readonly startDate: ISODate;
  readonly endDate: ISODate | null;
  readonly isCurrent: boolean;
  readonly description: string | null;
  readonly keyAchievements: readonly string[];
  readonly visibility: Visibility;
  readonly state: PublicationState;
  readonly publicationEligibility: PublicationEligibility;
  readonly ordering: number;
  readonly versionNo: number;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
}

export interface EducationRecordEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly institution: string;
  readonly degree: string;
  readonly fieldOfStudy: string | null;
  readonly startDate: ISODate;
  readonly endDate: ISODate | null;
  readonly isCurrent: boolean;
  readonly gradeOrHonors: string | null;
  readonly description: string | null;
  readonly visibility: Visibility;
  readonly state: PublicationState;
  readonly publicationEligibility: PublicationEligibility;
  readonly ordering: number;
  readonly versionNo: number;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
}

export interface CredentialRecordEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly name: string;
  readonly issuingOrganization: string;
  readonly credentialId: string | null;
  readonly credentialUrl: string | null;
  readonly issueDate: ISODate;
  readonly expirationDate: ISODate | null;
  readonly visibility: Visibility;
  readonly state: PublicationState;
  readonly publicationEligibility: PublicationEligibility;
  readonly ordering: number;
  readonly versionNo: number;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
}

export type ClaimSupportTargetType =
  | 'evidence'
  | 'capability'
  | 'skill'
  | 'project'
  | 'engineering_record'
  | 'experience'
  | 'education'
  | 'credential';

export interface ClaimSupportEntity {
  readonly id: EntityId;
  readonly claimId: EntityId;
  readonly ownerId: EntityId;
  readonly targetType: ClaimSupportTargetType;
  readonly targetId: EntityId;
  readonly createdAt: ISODateTime;
}

export type ResumeTargetAudience =
  'general' | 'software_engineering' | 'recruiter_summary' | 'project_focused' | 'job_specific';

export type ResumeState = 'draft' | 'preview' | 'published' | 'archived';

export interface ResumeVariantEntity {
  readonly id: EntityId;
  readonly ownerId: EntityId;
  readonly title: string;
  readonly slug: string;
  readonly privateDescription: string | null;
  readonly targetAudience: ResumeTargetAudience;
  readonly template: string;
  readonly visibility: Visibility;
  readonly state: ResumeState;
  readonly isPrimary: boolean;
  readonly presentationConfig: string;
  readonly versionNo: number;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
  readonly archivedAt: ISODateTime | null;
}

export type ResumeSectionKey =
  | 'summary'
  | 'experience'
  | 'education'
  | 'credentials'
  | 'claims'
  | 'skills'
  | 'capabilities'
  | 'projects'
  | 'custom';

export interface ResumeVariantSectionEntity {
  readonly id: EntityId;
  readonly variantId: EntityId;
  readonly ownerId: EntityId;
  readonly sectionKey: ResumeSectionKey;
  readonly title: string;
  readonly included: boolean;
  readonly ordering: number;
  readonly customHeading: string | null;
  readonly configJson: string;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
}

export type ResumeItemType =
  'experience' | 'education' | 'credential' | 'claim' | 'skill' | 'capability' | 'project';

export interface ResumeVariantItemEntity {
  readonly id: EntityId;
  readonly variantId: EntityId;
  readonly sectionId: EntityId;
  readonly ownerId: EntityId;
  readonly itemType: ResumeItemType;
  readonly itemId: EntityId;
  readonly customWording: string | null;
  readonly included: boolean;
  readonly ordering: number;
  readonly createdAt: ISODateTime;
  readonly updatedAt: ISODateTime;
}

export interface ResumeVariantVersionEntity {
  readonly id: EntityId;
  readonly variantId: EntityId;
  readonly ownerId: EntityId;
  readonly versionNo: number;
  readonly snapshotJson: string;
  readonly changeSummary: string | null;
  readonly createdAt: ISODateTime;
}
